### PR TITLE
snap: align with 22

### PR DESCRIPTION
**Pull request by Saviq**
This brings all the additional tools from g-t-t/22 aligning it better for backporting, and refreshes drm-info.

Because the contract between graphics-core20 providers and consumers isn't as strong, some of these may not work, depending on the provider.

### CODE REVIEW

**Comment by Saviq** [comment]
It may be useful to view the diff from main: https://github.com/MirServer/graphics-test-tools/compare/main...20-refresh.

**Comment by AlanGriffiths** [comment]
I expected `drm-info` to work, but it doesn't: "libjson-c.so not found"

**Comment by AlanGriffiths** [comment]
That just leaves the following (plausible) failures:

```
$ graphics-test-tools.vainfo
error: can't connect to X server!
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```
```
$ graphics-test-tools.vdpauinfo
display: :0   screen: 0
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
Error creating VDPAU device: 1
```
```
$ graphics-test-tools.vkcube
vkEnumerateInstanceExtensionProperties failed to find the VK_KHR_surface extension.

Do you have a compatible Vulkan installable client driver (ICD) installed?
Please look at the Getting Started guide for additional information.
```
```
$ graphics-test-tools.vulkaninfo
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
/build/vulkan-tools-KEbD_A/vulkan-tools-1.2.131.1+dfsg1/vulkaninfo/vulkaninfo.h:371: failed with ERROR_INCOMPATIBLE_DRIVER
```

**Comment by Saviq** [comment]
> Seems reasonable (although, as stated, not everything actually works)

Yes, mesa-core20 doesn't currently support VAAPI, VDPAU or Vulkan. It _could_, in theory, but that isn't a part of the current contract :)

**Pull request merged**
